### ISSUE TITLE
BUG: When discussion is created, error is thrown in notification service and no emails are sent

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/notifications#64]
**Describe the bug**
When discussion is created, error is thrown in notification service and no emails are sent.

**To Reproduce**

1. Go to https://dev.alkem.io/un-sdgs/challenges/food/community/discussions/new
2. Authenticate with ecoverse.member@alkem.io
3. Create new discussion - discussion is created successfully, **no emails are sent**
4. See notification service error
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0d940437-33ee-420a-bbb7-528524a5f765)

**Expected behavior**
All members of the community that have the flag for new discussions enabled, must receive email.

**Comment by techsmyth** [comment]
The error is only been thrown for the discussion.created.member template, the admin one sends just fine. And it also looks like the actual email template is being built ok - but that the error happens when we invoke notifyme. 

In general it is important to find a way to log and capture any errors arising from building this step - currently the errors cascade all the way up. Ideas @valentinyanakiev for how to capture / log errors from this?
